### ISSUE TITLE
error when removing agents

### ISSUE THREAD

**Issue by huckebrink** [JoelForamitti/agentpy#5]
Assume we have an agent that removes other agents from the simulation e.g. for simulating [predator-prey](https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations) I think I might have encountered a bug.
When removing an agent from the model/environment in step 1, the method is called on the agent again in the next step which leads to an  
```
AgentpyError
Agent 17 has no environment with topology '['grid', 'space', 'network']'
```

Here is a minimal example to reproduce the error:

```python
import agentpy as ap

class SomeAgent(ap.Agent):

    def do_things(self):
        for n in self.neighbors():
            print(f"removing: {n}")
            n.delete()
            break

class SomeModel(ap.Model):
    def setup(self, **kwargs):
        self.grid = self.add_grid([self.p.size] * 2)
        self.grid.add_agents(self.p.agent_count, SomeAgent, random=True)

    def step(self):
        self.agents.do_things()


if __name__ == "__main__":
    params ={
        "agent_count": 100,
        "size": 20,
        "steps": 100
    }

    model = SomeModel(params)
    results = model.run()
```

I also tried to call the  [remove_agents](https://agentpy.readthedocs.io/en/latest/reference_environments.html?highlight=remove#agentpy.Grid.remove_agents) function on the grid and model, but no luck.

Is this a bug, or am I doing it wrong?

Cheers

**Comment by JoelForamitti** [comment]
Hi @huckebrink , thanks for sharing such a clear example.

This error happens because `self.agents.do_things()` will loop through all agents in the model at the point of time it is called, so it is possible for an agent to get called by that loop after it got deleted. One way to solve this problem is to add the following at the beginning of `do_things`:

```
if self.env is None:
    return
```

I want think of a more elegant solution for the next update, however, so I will keep this issue open!

**Comment by huckebrink** [comment]
I expected that upon [deletion](https://agentpy.readthedocs.io/en/latest/reference_agents.html?highlight=delete#agentpy.Agent.delete), the agent would be "removed" from the environment and the model, as stated in the documentation. Thus, I expected the removed agent not to appear in `model.agents` in the following steps.  

This is the first thing that came to my mind, however, when looking at the code I struggle to come up with an implementation suggestion.

**Comment by JoelForamitti** [comment]
In the following steps, the agent is actually removed. The problem happens just within the same loop. 

Take the following example. You call `self.agents.do_things()` and start a loop over all 100 agents. Agent 1 is called first and happens to delete Agent 3. Then Agent 2 is called, all fine. But then Agent 3 is called, because it is still in the queue as it was still alive when `self.agents.do_things()` was called. Since Agent 3 is deleted, this causes an Error.

I hope this clarifies the situation. I will think of a way to solve this!

**Comment by zba18** [comment]
> Hi @ huckebrink , thanks for sharing such a clear example.
> 
> This error happens because `self.agents.do_things()` will loop through all agents in the model at the point of time it is called, so it is possible for an agent to get called by that loop after it got deleted. One way to solve this problem is to add the following at the beginning of `do_things`:
> 
> ```
> if self.env is None:
>     return
> ```
> 
> I want think of a more elegant solution for the next update, however, so I will keep this issue open! Ideas welcome :)

Is it right to guess that execution queue-pool is filled with `agent.do_things()` which is populated at the start of every model `step()`? 

If removal of agents is a common use-case, maybe it's justified to add a wrapper around each `agent.do_things()` function which verifies the existence of the `agent` in the environment (as above) before it is able to `do_things()` ? 

Otherwise, the hack above would be **the** necessary practice for the removing agents within experiments

**Comment by JoelForamitti** [comment]
That is a good idea! It would have to detect wether the element is still in the list `agents`. One way to do that could be to change the `AttrList` class from a list to an iterator over its parent list. I will try that out

**Comment by JoelForamitti** [comment]
I added two features two address this issue in https://github.com/JoelForamitti/agentpy/pull/6:

First, there is a new method `AgentList.call` with an argument `check_alive` that can be used to prevent looping over deleted agents.

Second, `Agent.neighbors` can now also be called for agents without an environment, and will return an empty list instead of an error.
